/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author andrei
 */
public class Acasa extends javax.swing.JFrame {

    /**
     * Creates new form Acasa
     */
    public Acasa() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAdaugaStudentButton = new javax.swing.JButton();
        jAdaugaCarteButton = new javax.swing.JButton();
        jStatisticaButton = new javax.swing.JButton();
        jImprumutaCarteButton = new javax.swing.JButton();
        jIesireButton = new javax.swing.JButton();
        jReturneazaCarteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jAdaugaStudentButton.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jAdaugaStudentButton.setIcon(new javax.swing.ImageIcon("/Users/andrei/Desktop/Java/member-add-on-300x300.png")); // NOI18N
        jAdaugaStudentButton.setText("Adăugă student");
        jAdaugaStudentButton.setIconTextGap(8);
        jAdaugaStudentButton.setMaximumSize(new java.awt.Dimension(150, 150));
        jAdaugaStudentButton.setMinimumSize(new java.awt.Dimension(150, 150));
        jAdaugaStudentButton.setPreferredSize(new java.awt.Dimension(159, 59));
        jAdaugaStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdaugaStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jAdaugaStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 395, 56));

        jAdaugaCarteButton.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jAdaugaCarteButton.setIcon(new javax.swing.ImageIcon("/Users/andrei/Desktop/Java/New book.png")); // NOI18N
        jAdaugaCarteButton.setText("Adaugă carte");
        jAdaugaCarteButton.setIconTextGap(8);
        jAdaugaCarteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdaugaCarteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jAdaugaCarteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 395, -1));

        jStatisticaButton.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jStatisticaButton.setIcon(new javax.swing.ImageIcon("/Users/andrei/Desktop/Java/Statics.png")); // NOI18N
        jStatisticaButton.setText("Statistică");
        getContentPane().add(jStatisticaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 80, 337, -1));

        jImprumutaCarteButton.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jImprumutaCarteButton.setIcon(new javax.swing.ImageIcon("/Users/andrei/Desktop/Java/borrow book.png")); // NOI18N
        jImprumutaCarteButton.setText("Împrumută carte");
        jImprumutaCarteButton.setPreferredSize(new java.awt.Dimension(159, 59));
        jImprumutaCarteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jImprumutaCarteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jImprumutaCarteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 395, 56));

        jIesireButton.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jIesireButton.setIcon(new javax.swing.ImageIcon("/Users/andrei/Desktop/Java/exit.png")); // NOI18N
        jIesireButton.setText("Ieșire");
        jIesireButton.setIconTextGap(8);
        jIesireButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIesireButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jIesireButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 150, 337, -1));

        jReturneazaCarteButton.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jReturneazaCarteButton.setIcon(new javax.swing.ImageIcon("/Users/andrei/Desktop/Java/return book png.jpeg")); // NOI18N
        jReturneazaCarteButton.setText("Returnează carte");
        jReturneazaCarteButton.setIconTextGap(8);
        jReturneazaCarteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReturneazaCarteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jReturneazaCarteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 395, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/andrei/Desktop/Java/Library_Book_532388_1366x768.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAdaugaCarteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdaugaCarteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAdaugaCarteButtonActionPerformed

    private void jAdaugaStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdaugaStudentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAdaugaStudentButtonActionPerformed

    private void jIesireButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIesireButtonActionPerformed
        setVisible(false); 
        new Login().setVisible(true);
    }//GEN-LAST:event_jIesireButtonActionPerformed

    private void jReturneazaCarteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReturneazaCarteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jReturneazaCarteButtonActionPerformed

    private void jImprumutaCarteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jImprumutaCarteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jImprumutaCarteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acasa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdaugaCarteButton;
    private javax.swing.JButton jAdaugaStudentButton;
    private javax.swing.JButton jIesireButton;
    private javax.swing.JButton jImprumutaCarteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jReturneazaCarteButton;
    private javax.swing.JButton jStatisticaButton;
    // End of variables declaration//GEN-END:variables
}
