/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author andrei
 */
public class AdaugaCarte extends javax.swing.JFrame {

    /**
     * Creates new form AdaugaCarte
     */
    public AdaugaCarte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCodStudentText = new javax.swing.JLabel();
        jNumeStudentText = new javax.swing.JLabel();
        jPrenumeStudentText = new javax.swing.JLabel();
        jFacultateStudentText = new javax.swing.JLabel();
        jNivelStudentText = new javax.swing.JLabel();
        jCodStudentTextField = new javax.swing.JTextField();
        jNumeStudentTextField = new javax.swing.JTextField();
        jPrenumeStudentTextField = new javax.swing.JTextField();
        jFacultateStudentComboBox = new javax.swing.JComboBox<>();
        jNivelStudentComboBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jInchideStudentButton = new javax.swing.JButton();
        jSalveazaStudentButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCodStudentText.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jCodStudentText.setText("Cod student");
        getContentPane().add(jCodStudentText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jNumeStudentText.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jNumeStudentText.setText("Nume");
        getContentPane().add(jNumeStudentText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jPrenumeStudentText.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jPrenumeStudentText.setText("Prenume");
        getContentPane().add(jPrenumeStudentText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jFacultateStudentText.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jFacultateStudentText.setText("Facultate");
        getContentPane().add(jFacultateStudentText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jNivelStudentText.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jNivelStudentText.setText("Nivel");
        getContentPane().add(jNivelStudentText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        jCodStudentTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jCodStudentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodStudentTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(jCodStudentTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 303, 33));

        jNumeStudentTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        getContentPane().add(jNumeStudentTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 303, 29));

        jPrenumeStudentTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        getContentPane().add(jPrenumeStudentTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 303, 31));

        jFacultateStudentComboBox.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jFacultateStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facultate de Automatica si Calculatoare", "Facultatea de Autovehicule Rutiere, Mecatronica si Mecanica", "Facultatea de Constructii", "Facultatea de Electronica si Comunicatii", "Facultatea de Inginerie a Instalatiilor", "Facultatea de Inginerie Electrica", "Facultatea de Stiinte", "Facultatea de Inginerie" }));
        getContentPane().add(jFacultateStudentComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 303, 31));

        jNivelStudentComboBox.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jNivelStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licenta", "Master", "Doctorat" }));
        getContentPane().add(jNivelStudentComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 303, 31));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(965, 68, -1, 296));

        jInchideStudentButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jInchideStudentButton.setIcon(new javax.swing.ImageIcon("/Users/andrei/Desktop/Java/red-x-mark-transparent-background-3.png")); // NOI18N
        jInchideStudentButton.setText("Închide");
        jInchideStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInchideStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jInchideStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 317, 170, 50));

        jSalveazaStudentButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jSalveazaStudentButton1.setIcon(new javax.swing.ImageIcon("/Users/andrei/Desktop/Java/save-icon--1.png")); // NOI18N
        jSalveazaStudentButton1.setText("Salvează");
        jSalveazaStudentButton1.setIconTextGap(8);
        jSalveazaStudentButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalveazaStudentButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jSalveazaStudentButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 170, 50));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/andrei/Desktop/Java/123456.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCodStudentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodStudentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCodStudentTextFieldActionPerformed

    private void jInchideStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInchideStudentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInchideStudentButtonActionPerformed

    private void jSalveazaStudentButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalveazaStudentButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSalveazaStudentButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdaugaCarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdaugaCarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdaugaCarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdaugaCarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdaugaCarte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCodStudentText;
    private javax.swing.JTextField jCodStudentTextField;
    private javax.swing.JComboBox<String> jFacultateStudentComboBox;
    private javax.swing.JLabel jFacultateStudentText;
    private javax.swing.JButton jInchideStudentButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jNivelStudentComboBox;
    private javax.swing.JLabel jNivelStudentText;
    private javax.swing.JLabel jNumeStudentText;
    private javax.swing.JTextField jNumeStudentTextField;
    private javax.swing.JLabel jPrenumeStudentText;
    private javax.swing.JTextField jPrenumeStudentTextField;
    private javax.swing.JButton jSalveazaStudentButton1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
