
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Andrei Palii
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); // fac pagina fullscreen
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNumeUserText = new javax.swing.JLabel();
        jParolaText = new javax.swing.JLabel();
        jLoginTextField = new javax.swing.JTextField();
        jParolaTextField = new javax.swing.JPasswordField();
        jButtonIntrare = new javax.swing.JButton();
        jButtonIesire = new javax.swing.JButton();
        jSeparator = new javax.swing.JSeparator();
        jBibliotecaUTCNText = new javax.swing.JLabel();
        jLabelCuBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jNumeUserText.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jNumeUserText.setText("Nume user");
        getContentPane().add(jNumeUserText, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, -1, -1));

        jParolaText.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jParolaText.setText("Parola");
        getContentPane().add(jParolaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, -1, -1));

        jLoginTextField.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLoginTextField.setForeground(new java.awt.Color(51, 0, 51));
        jLoginTextField.setToolTipText("");
        jLoginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(jLoginTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, 175, 35));

        jParolaTextField.setForeground(new java.awt.Color(51, 0, 51));
        jParolaTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jParolaTextFieldCaretUpdate(evt);
            }
        });
        jParolaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jParolaTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(jParolaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 340, 175, 33));

        jButtonIntrare.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonIntrare.setIcon(new javax.swing.ImageIcon("/Users/andrei/Desktop/Java/login.png")); // NOI18N
        jButtonIntrare.setText("Intrare");
        jButtonIntrare.setIconTextGap(8);
        jButtonIntrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIntrareActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIntrare, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 136, 43));

        jButtonIesire.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonIesire.setIcon(new javax.swing.ImageIcon("/Users/andrei/Desktop/Java/red-x-mark-transparent-background-3.png")); // NOI18N
        jButtonIesire.setText("Ieșire");
        jButtonIesire.setIconTextGap(5);
        jButtonIesire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIesireActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIesire, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, 157, 43));

        jSeparator.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 326, 17));

        jBibliotecaUTCNText.setFont(new java.awt.Font("Helvetica", 0, 36)); // NOI18N
        jBibliotecaUTCNText.setText("Biblioteca UTCN");
        getContentPane().add(jBibliotecaUTCNText, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, -1, -1));

        jLabelCuBackground.setIcon(new javax.swing.ImageIcon("/Users/andrei/Desktop/Java/Login background.PNG")); // NOI18N
        getContentPane().add(jLabelCuBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIesireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIesireActionPerformed
        System.exit(0); // ies din program cu "codul" 0
    }//GEN-LAST:event_jButtonIesireActionPerformed

    private void jLoginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginTextFieldActionPerformed

    private void jButtonIntrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIntrareActionPerformed

        if (jLoginTextField.getText().equals("Andrei") && jParolaTextField.getText().equals("SSATR")) {
            
            setVisible(false); // dispare login page daca conditia e satisfacuta (login && pass corespund)
            new Acasa().setVisible(true); // dupa logare apare pagina "Acasa"
        }
        
        else {
            
            JOptionPane.showMessageDialog(null, "Nume utilizator sau parolă incorectă");
        }
    }//GEN-LAST:event_jButtonIntrareActionPerformed

    private void jParolaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jParolaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jParolaTextFieldActionPerformed

    private void jParolaTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jParolaTextFieldCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jParolaTextFieldCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBibliotecaUTCNText;
    private javax.swing.JButton jButtonIesire;
    private javax.swing.JButton jButtonIntrare;
    private javax.swing.JLabel jLabelCuBackground;
    private javax.swing.JTextField jLoginTextField;
    private javax.swing.JLabel jNumeUserText;
    private javax.swing.JLabel jParolaText;
    private javax.swing.JPasswordField jParolaTextField;
    private javax.swing.JSeparator jSeparator;
    // End of variables declaration//GEN-END:variables
}
